name: Windows latest

on:

  workflow_dispatch:

  schedule:
    - cron: '34 19 * * 0'

jobs:
  build:

    runs-on: windows-latest

    env:
      VCPKG_INSTALLATION_ROOT: C:\vcpkg
      VCPKG_ROOT: C:\vcpkg

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.*.*'

    - name: Set up vcpkg binary cache
      run: |
        mkdir -p ${{ github.workspace }}/vcpkg_cache
        echo "VCPKG_DEFAULT_BINARY_CACHE=${{ github.workspace }}/vcpkg_cache" >> $env:GITHUB_ENV

    - name: Cache vcpkg binary artifacts
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: ${{ runner.os }}-vcpkg-bin-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-bin-

    - name: Get all repositories
      run: |
        git clone https://github.com/jhu-cisst/cisst-saw --recursive ${{github.workspace}}/cisst-saw
        cd ${{github.workspace}}/cisst-saw
        git submodule foreach git checkout devel
        git submodule foreach git submodule init
        git submodule foreach git submodule update

    - name: Create cisstNetlib build directory
      run: |
        cmake -E make_directory ${{github.workspace}}/cisstNetlib-build

    - name: Build cisstNetlib
      working-directory: ${{github.workspace}}/cisstNetlib-build
      run: |
        cmake ${{github.workspace}}/cisst-saw/cisstNetlib -DcisstNetlib_LANGUAGE=C
        cmake --build . --config Release
        cmake --build . --target install

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: |
        cmake ${{github.workspace}}/cisst-saw -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake" -C ${{github.workspace}}/.github/workflows/cmake-windows-cache.cmake
        cmake ${{github.workspace}}/cisst-saw

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        cmake --build . --config Release
